<a href="https://colab.research.google.com/github/Nanobot234/CSC44800Dev/blob/master/Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Part 1: Loading Dataset

In [17]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_scorehttps://colab.research.google.com/github/Nanobot234/CSC44800Dev/blob/master/Assignment3.ipynb
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import PolynomialFeatures
import ssl


ssl._create_default_https_context = ssl._create_unverified_context #This was needed to allow me to load the github link(had to do with certificates)


# Using pandas load the dataset (load remotely, not locally)
# Output the first 15 rows of the data

#first will import the data


slimedata = pd.read_csv("https://raw.githubusercontent.com/profmcnich/example_notebook/main/science_data_large.csv",header = None)

# Output the first 15 rows of the data
print(slimedata.head(15)) #

#Displaying summary of the table information 
print(" ")

print(slimedata.info())



                 0         1            2
0   Temperature °C  Mols KCL    Size nm^3
1              469       647  624474.2571
2              403       694  577961.0286
3              302       975  619684.7143
4              779       916  1460449.029
5              901        18  43257.25714
6              545       637     712463.4
7              660       519  700696.0286
8              143       869  271826.0286
9               89       461  89198.02857
10             294       776  477021.0286
11             991       117  244177.1143
12             307       781  500645.4571
13             206        70        31452
14             437       599  539021.4571
15             566        75  91852.71429
 
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       1001 non-null   object
 1   1       1001 non-null   object
 2   2       1001 non-null   objec

# Part 2: Splitting Dataset

In [18]:

# Take the pandas dataset and split it into our features (X) and label (y)

temps_heat_x = slimedata.iloc[1:1000,0:2] #ignores the top labels

size_y = slimedata.iloc[1:1000,2] 


# Use sklearn to split the features and labels into a training/test set. (90% train, 10% test)

X_train, X_test, y_train, y_test = train_test_split(temps_heat_x, size_y, train_size=0.9, test_size=0.10, random_state=50)

print(X_train) #Testting I did

print(y_train) #Just for testing and things




       0    1
627  529  203
244  197  572
655  102  710
583  862  491
854  972  620
..   ...  ...
290  372  944
110  417  186
908  943  269
481   87  449
689  320  899

[899 rows x 2 columns]
627       222299.4
244    237080.1143
655    160466.8571
583    863716.0286
854    1227926.857
          ...     
290    732261.0286
110    161116.4571
908    520717.4571
481    84930.02857
689    602291.4571
Name: 2, Length: 899, dtype: object


# Linear Regression

In [19]:
# Use sklearn to train a model on the training set

regression = LinearRegression().fit(X_train,y_train)

print("The regression score is {}".format(regression.score(X_train,y_train)))

# Create a sample datapoint and predict the output of that sample with the trained model
sample = np.array([[353,562]])
regression.predict(sample) 



The regression score is 0.859694884847547


array([473243.81312741])

The score is the coefficient of determination, or in other words how accurate of a prediction the model is of the data, mine is a good accuracy

In [20]:
# Extract the coefficents and intercept from the model and write an equation for your h(x) using LaTeX

print("Regression coefficients {}".format(regression.coef_))

print("Intercept {}".format(regression.intercept_))



Regression coefficients [ 869.96391647 1020.41465467]
Intercept -407326.4853104513


$h(x) = 869.96391 * x_0 + 1020.41465 * x_1 - 407326.485310$

# Part 4: Cross Validation

In [21]:
# Use the cross_val_score function to repeat your experiment across many shuffles of the data
scores = cross_val_score(regression,X_train,y_train)
print(scores)
# Report on their finding and their significance

[0.87070557 0.83938366 0.84753474 0.86356901 0.86121424]


The cross val scores are significant because after many shuffles of the data, the scores are still relatively similar with minor variances. This shows that the model is effective in predicitng our data even with  random changes in the data

# Part 5: Using Another Polynomial Regression

In [16]:
# Using the PolynomialFeatures library perform another regression on an augmented dataset of degree 2
from sklearn import linear_model

polyN = PolynomialFeatures(2)
X_TRAIN = polyN.fit_transform(X_train)
X_datatest = polyN.fit_transform(X_train) #transform test set

print(X_TRAIN)

bayReg = linear_model.BayesianRidge().fit(X_TRAIN,y_train) #

# Report on the metrics and output the resultant equation as you did in Part 3.

print(" ")

print("Prediction given data is {}".format(bayReg.predict(X_datatest)))

print(" ")

print("Score is {}".format(bayReg.score(X_TRAIN,y_train)))

print(" ")

print("Coefficient is {}".format(bayReg.coef_))

print("Intercept is {}".format(bayReg.intercept_))





[[1.00000e+00 5.29000e+02 2.03000e+02 2.79841e+05 1.07387e+05 4.12090e+04]
 [1.00000e+00 1.97000e+02 5.72000e+02 3.88090e+04 1.12684e+05 3.27184e+05]
 [1.00000e+00 1.02000e+02 7.10000e+02 1.04040e+04 7.24200e+04 5.04100e+05]
 ...
 [1.00000e+00 9.43000e+02 2.69000e+02 8.89249e+05 2.53667e+05 7.23610e+04]
 [1.00000e+00 8.70000e+01 4.49000e+02 7.56900e+03 3.90630e+04 2.01601e+05]
 [1.00000e+00 3.20000e+02 8.99000e+02 1.02400e+05 2.87680e+05 8.08201e+05]]
Prediction given data is [2.22299400e+05 2.37080114e+05 1.60466857e+05 8.63716029e+05
 1.22792686e+06 3.39907314e+05 3.19123400e+05 5.13347114e+05
 2.17334314e+05 1.04956829e+05 1.18457029e+05 2.87802714e+05
 1.86678314e+05 1.42239803e+06 2.98081029e+05 1.78553203e+06
 9.20531314e+05 1.24874203e+06 1.16260029e+05 5.38421457e+05
 1.73630100e+06 5.44500029e+05 3.63689257e+05 6.54204286e+04
 7.12463400e+05 1.88056114e+05 4.92524600e+05 8.29200314e+05
 1.26718971e+06 1.81699114e+05 8.51571314e+05 4.56082714e+05
 4.55983857e+05 7.61464000e+04 

$$ h(X) = 0.00000000e+00*x_0 + 1.20000000e+01*x_1 + -1.08506623e-07*x_2 + -4.08004186e-12*x_3 + 2.00e+00*x_4 + 2.85714287e-02*x_5 + 1.5495228581130505e-05$$